# Generated by Django 5.0.6 on 2024-06-21 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usrvisit', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagevisit',
            old_name='urlPath',
            new_name='path',
        ),
    ]
